### ISSUE TITLE
"Updates" section erased after update r53331

### ISSUE THREAD

**Issue by lalalasupa0** [null2264/yokai#106]
### Steps to reproduce

Open updates section

### Expected behavior

Should show the usual new stuff

### Actual behavior

![Screenshot_20240620_033527_Ykai Nightly](https://github.com/null2264/yokai/assets/101371218/cb2a0728-bb10-4272-8314-4e2a1e2abe81)

### Yōkai version

Nightly r5333

### Android version

Android 12

### Device

Samsung S10+

### Other details

Happened exatly after r5331

History section is alright, the issue is with Updates

And I updated my library some time ago before updating... 'Lost some stuff there ~ . ~

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, or a request for an extension, I should be contacting the extensions repository's maintainer/support for help.
- [X] I am reporting an issue exclusive to this fork. I have also checked that is not an issue on the [main version of Mihon](https://github.com/mihonapp/mihon)
- [X] I have tried the [troubleshooting guide](https://mihon.app/help/).
- [X] I have updated the app to version **[1.8.4](https://github.com/null2264/yokai/releases/latest)**.
- [X] I have updated all installed extensions.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I have filled out all of the requested information in this form.

**Comment by lalalasupa0** [comment]
Fixed when updating the library again (I didn't update it again the first time I saw it was erased)

**Comment by null2264** [comment]
I don't think it's fixed, I just replicated the issue.

The data seems to be there, but not shown in "Updates" tab, you can see them in "All" tab

**Comment by null2264** [comment]
Got it fixed on https://github.com/null2264/yokai/commit/7926590c222e973f4220d161426c8db45ccd4c20
